language: objective-c
osx_image: xcode8
xcode_project: PitchSpellingTools.xcodeproj
xcode_scheme: PitchSpellingToolsMac
xcode_sdk: macosx
before_script:
  - carthage bootstrap

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
